# Site settings
title: FI Labs
header-img: img/home-bg.jpg
email: contact@ficonsulting.com
copyright_name: FI Consulting
description: "Research and Development Division of FI Consulting"
#baseurl: "/startbootstrap-clean-blog-jekyll"
baseurl: "/filabs"
url: "http://www.ficonsulting.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  contact@ficonsulting.com
blogroll : true

# Google Analytics
google_tracking_id: UA-93971920-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
